server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "configserver:http://localhost:8888"

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/users/**

        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/api/books/**
          filters:
            - AuthenticationFilter

        - id: borrowing-service
          uri: lb://BORROWING-SERVICE
          predicates:
            - Path=/api/borrowing/**
          filters:
            - name: RequestHeader
              args:
                name: Internal-Call
                value: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/